oep-template.rst
oeps/oep-0001.rst

The purpose of this pull request is to add support for proposing changes to the
functionality of the Open edX platform to the OEP process. Rather than
using multiple processes, I believe the OEP process can be easily
adapted to this case, particularly with some light support for less technical
forms of discussion.
Changelog:
* New "Product" proposal type
* Remove references to arch@ email address
* Created "Inital Submission" section
* Increased scope of Arbiter role to include helping with GitHub and other
technical mechanics as needed
* Added support for Google Docs and other external forums for discussion of
the proposal
* Added "References" field to the table as a place to put links to external
discussions

Add support for product changes to OEP-1

---

.gitignore
oep-template.rst
oeps/conf.py
oeps/oep-0001.rst
oeps/oep-0002.rst
oeps/oep-0003.rst
oeps/oep-0004.rst
oeps/oep-0005.rst
requirements.txt

Use the new edx-sphinx-theme package for the output, and remove the explicit copyright footer from each page which is now put there by the theme.  (This will need to be done for the new OEPs already created in pending PRs too.)  Also flesh out the .gitignore file with a few IDE and editor artifacts, etc.
Before merging, we should make sure that the Read the Docs project is configured to build in a virtualenv and install the dependencies from requirements.txt.

PLAT-1084 Use edx-sphinx-theme for output

---

oeps/oep-0006.rst

This is an OEP for context-scoped XBlock fields, also called "course-scoped XBlock fields."
@efagin can you please check this over and assign an arbiter?

OEP-6: Context-scoped XBlock Fields

---

oeps/oep-0002.rst

When updating [openedx.yaml](https://github.com/edx/edx-analytics-pipeline/blob/5b3a6db1e466a18d67cc74c0a4c98e2c3906290d/openedx.yaml) for edx-analytics-pipeline as part of the OEP-5 adoption work. I discovered that many OEPs don't really apply to the data pipeline. However, there was no way for me to mark those OEPs as "not applicable" so any automated reports would just assume that this repo was not compliant.
A reasonable argument could also be made for just setting the `state` to `True` in those cases, but I think I prefer the explicit third state.
FYI @cpennington

Add a "Not Applicable" state to OEP-2

---

oeps/oep-0007.rst

Plan for migrating Open edX code to Python 3.

OEP-7: Python 3 migration plan

---

README.rst

I clicked on the wrong link to the wrong docs.  I can't imagine I'd be the last person to make that mistake.  I think it would be better to make the link clear that it isn't for OERs, and let someone find that if they need to.

Make README link to docs less confusing.

---

oeps/oep-0015.rst

Submitting this as an OEP per [the discussion on edx-code](https://groups.google.com/forum/#!topic/edx-code/T83TDxhH74E/discussion). Here's a copy of the abstract as of January 24, 2017 (see [the current OEP draft](https://github.com/msegado/open-edx-proposals/blob/oep15/oeps/oep-0015.rst) for any changes):
> ## Abstract
> The Open edX platform is a powerful tool for both content authoring and learning-sciences research, in part due to its support for including arbitrary JavaScript in course materials; for example, such scripts can enable researchers to conduct novel experiments and log custom learner interaction events for analysis. Unfortunately, deploying and maintaining JavaScript assets across an entire course (or multiple courses) is a significant challenge, especially in …

OEP-15: Course-wide Custom JavaScript

---

oeps/oep-0007.rst

Per https://github.com/edx/XBlock/pull/365#issuecomment-318447063, noting an issue that bit me while trying to use a recently-converted-to-python3 XBlock distribution in the runs-on-python2 edx-ora2 codebase.
@jmbowman, would you mind reviewing? No rush.

Note 'no unicode in setup.py metadata' gotcha

---

oeps/oep-0018-bp-python-dependencies.rst

Recommendations for managing python package dependencies which should help minimize problems over time.  The key technology choice involved is `pip-tools`, which we already use in many of our repositories.  The current draft specifies that we should use a service to auto-generate PRs with requirement updates, but stops short of recommending which one to use (largely because we're still in the process of finalizing that decision, and the choice may change over time anyway).

OEP-0018: Python Dependency Management

---

adr-based-template.rst
external-link-template.rst
oeps/oep-0001.rst
pep-based-template.rst

This PR updates and simplifies the OEP process defined in OEP-1 even further than [PR-53](https://github.com/edx/open-edx-proposals/pull/53).
**Review Period**
May 02, 2018 -> May 11, 2018
**Arbiter**
@cpennington 
**Motivation**
Going forward, we want to encourage teams to write down and propose their architectural and system-wide decisions so we can align with best practices, processes, and system architectures.
Our hypothesis is that the rigid structure required by the PEP-based OEP template deters and confuses authors.  Also, we find that some authors continue to prefer other documentation and discussion tools.  So this PR introduces 2 other OEP templates to accommodate those needs:
- ADR-based template (much simpler format than PEP)
- External-link catered template (requiring …

OEP-0001: Simplify even further for OEP authors

---

oeps/oep-0022-bp-django-caches.rst

OEP-0022: Caching in Django
This OEP provides some best practice regarding coding using Django caches. This includes some less proven direction as well, with the expectation that this OEP will be updated over time to keep up with recommendations and better clarify recommendations as share libraries become available.
FYI: @BenjiLee, @nasthagiri

OEP-0022: Caching in Django

---

oeps/oep-0018-bp-python-dependencies.rst

The verbose output of ``pip-compile`` has been improved in recent versions to include information useful in tracking down the source of conflicting version constraints.  Updated the troubleshooting section to recommend utilizing that.

Add pip-compile -v tip to OEP-18

---

oeps/oep-0014-proc-archive-repos.rst

I was going through these docs to archive a tools repo and noticed it still references Gemnasium in the steps. Gemnasium is no longer an active service, so we should remove that from the docs (https://docs.gitlab.com/ee/user/project/import/gemnasium.html).
It should probably stay in the motivation/ rejected alternatives, as it was still a contributing factor to this OEP.

Remove gemnasium step from OEP-0014

---

oeps/oep-0002-bp-repo-metadata.rst

Per @nedbat This is now obselete and should be removed from any existing `openedx.yaml` files.
Let me know if there's a more preferred way of stating this in the doc.

Make track-pulls option obsolete in OEP-2

---

oeps/oep-0002-bp-repo-metadata.rst

Since owners are people but teams support an owner.  Reflect that in the metadata.

Reflect new ownership thinking in metadata.

---

oeps/oep-0014-proc-archive-repos.rst
oeps/oep-0021-proc-deprecation.rst

These are mostly minor updates to these OEPs to point to the discourse forum instead of edx-code, but I am also switching over the role of arbiter on OEP-0021 to @tuchfarber .

Update OEPs for announcements and switch ownership.

---

oeps/oep-0002-bp-repo-metadata.rst
oeps/oep-0010-proc-openedx-releases.rst

People seem chronically confused about the use of `openedx-release` is openedx.yaml files.  Try to clarify.

Clarify the use of openedx-releases keys in openedx.yml files

---

oeps/oep-templates/adr-based-template.rst
oeps/oep-templates/external-link-template.rst
oeps/oep-templates/pep-based-template.rst

- No reason to italicize some of the table sections
- Use the "Open edX" trademark correctly
- Link to the latest Discourse instance

Tweak the OEP templates

---

oeps/oep-0002-bp-repo-metadata.rst

This PR updates **OEP-2 Repository Metadata** to propose new practices for ownership bookkeeping and designation in our edX repositories.
Nov 25, 2019 -> Dec 9, 2019
@cpennington 
At a high level, this PR proposes the following:
1. ownership is assigned to squads (i.e., teams with 5-6 people each) as opposed to individuals
2. owners are assigned at the granularity of higher-level, business-aligned functionality (user-facing services, user-facing apps, and system-wide frameworks)
3. lower-level repos are indirectly assigned owners through assignment to dependent higher-level repos
See the rationale listed in the PR.  Essentially:
1. We'd like for healthy and longer-lasting teams to be steady and responsible technical stewards of the things they own.
2. We'd like to have more meaningful …

OEP-2: Updates to Ownership Assignment Metadata

---

oeps/oep-0021-proc-deprecation.rst

In the context of dead code, feature toggles could hide old code that if active could carry on significant damage.
Here's a reference to an U.S. Securities and Exchange Commission act where they order the cease and desist to a company that lost more than 400 million in trading transactions due to a repurposed "flag".
I believe this fits here, rather than in OEP-17, because this OEP-21 is somehow a detailed expansion of the "Removal" section in OEP-17 and most importantly, this OEP-21 includes a broader solution to mitigate the risk. The horror tale may also apply to configurations options and not necessarily toggles.

Add a horror tale when dead code is not removed

---

oeps/oep-0030-arch-pii-markup-and-auditing.rst

These two code-blocks without a language specifier were not being rendered on ReadTheDocs; rather than specifying `none`, just use a regular rST code block.

Fix code blocks that were omitted by RTD; fix typos

---

oeps/oep-0047-bp-semantic-versioning.rst

Note: This OEP on Semantic Versioning was split out from https://github.com/edx/open-edx-proposals/pull/140

OEP-47: Semantic Versioning

---

oeps/oep-0002-bp-repo-metadata.rst

See for more details: https://openedx.atlassian.net/browse/ARCHBOM-1206
Originally, the intention was to openedx.yaml as the source of truth for ownership info. However, as the ownership initiative has progressed, the [ownership google sheet](https://docs.google.com/spreadsheets/d/1qpWfbPYLSaE_deaumWSEZfz91CshWd3v3B7xhOk5M4U/edit#gid=840878297) has become the source. It was decided asking everyone to switch to openedx.yaml as source of truth is not necessary in the short term and would distract from other things that need to be done for the ownership effort. 
The change in this PR is meant to align OEP-2 with current plans for ownership.

[ARCHBOM-1206] Modifying OEP2: Make owner key optional

---

oeps/oep-0045-arch-ops-and-config.rst

This OEP is under review from **2020-04-17 though 2020-05-04.**
The goal is to vet the proposed end state before we start talking about how to get there to make sure that the proposal properly outlines and answers major questions about how to operate and configure Open edX in this future state. 
We are keeping this review period relatively short because, based on early feedback, we don't expect it to be a particularly controversial goal.  Agreeing on this OEP quickly will allow us to move the conversation over to implementation strategies where we expect there to be more diverse needs to take into consideration.  If it turns out to be more controversial than anticipated we will extend the review period to accommodate more feedback.
The implementation discussion will happen in [this …

OEP-45 Operating and Configuring Open edX

---

oeps/oep-0041-arch-async-server-event-messaging.rst

This OEP describes the general format and conventions Open edX should use in asynchornous event messaging across services. These events would be emitted when a service has taken some action to data that it owns, and that other services would be interested in. This could be a course publish, a user enrollment, updates to catalog metadata, etc.
This OEP does not cover:
* Remote Prodecure Calls, i.e. using messaging to send commands to other services. Events in this document are the services broadcasting, "Here is what I just did!" to interested parties, not "Please do this thing for me!"
* Real-time streaming of student learning events to external platforms, as detailed in [OEP-26](https://open-edx-proposals.readthedocs.io/en/latest/oep-0026-arch-realtime-events.html), though it is possible …

OEP-41: Asynchronous Server Event Message Format

---

oeps/oep-0014-proc-archive-repos.rst

There are a lot of options for this but choosing the simplest for now
since this is a pretty corner case and it's unclear how often this will
happen let alone how often it will bite us to not have a more complex
process here.
Currently there are only 5 forks under edx-unsupported that could have
collisions, 4 of which we are unlikely to fork again.

Provide guidance for archiving forks multiple times.

---

oeps/oep-0026-arch-realtime-events.rst

Not knowing how to direct sphinx + read-the-docs to the correct document, this PR fixes broken links by updating the links to point to Github links directly.

OEP-26: Fix read-the-doc links for xAPI/Caliper

---

oeps/oep-0026/caliper-realtime-events.rst
oeps/oep-0026/xapi-realtime-events.rst

Caliper spreadsheet had previously become inaccessible. This should reduce
the risk of that happening again.

fix: Use copy of spreadsheet owned by edX Google account

---

oeps/conventional-commits.rst
oeps/oep-0051-bp-conventional-commits.rst

A provisional OEP for conventional commits.
Original description:
> Mostly, this just establishes the guideline, points at the spec, and
> clarifies what we will and will not do.

docs: OEP-0051, Conventional Commits

---

oeps/conventional-commits.rst
oeps/oep-0051-bp-conventional-commits.rst

This is an OEP for Conventional Commits. This establishes the guidelines, points at the third-party public spec, and
clarifies what we will and will not do.
Our goal now is to have an OEP that we can put into practice, then iterate.
Previous review and discussion is in another pull request: #182.

OEP-0051 Conventional Commits

---

oeps/oep-0051-bp-conventional-commits.rst

The table wasn't appearing because the last cell had three columns.  Use
the correct syntax to make the last cell have a bullet list in it.

fix: use correct rst table syntax and add toc

---

oeps/conf.py
oeps/oep-0005-arch-containerize-devstack.rst

Adding "Edit on Github" button to make it easier to correct documentation
Adding decisions to OEP-0005 to increase visibility. This potentially creates an informal standard for how to add decisions to oeps.

docs: Adding Decisions section to OEP-005 + feat: Adding Edit on Github button

---

oeps/oep-0037-bp-test-data.rst

What's in this PR:
- name changes
- Modifying the flow of how data is loaded. Before, the OEP was suggesting something more general. During the POC, we opted for a very specific implementation, where we assume we'll always use an yaml file to specify data. I think this should go in OEP rather than ADR. Mostly cause of how much space OEP-37 gives to loading data.

docs: modifying OEP to match POC implementation

---

oeps/oep-0001.rst
oeps/oep-0003-arch-async-tasks.rst
oeps/oep-0006-arch-context-xblock-fields.rst
oeps/oep-0009-bp-permissions.rst
oeps/oep-0012-arch-fragment-views.rst
oeps/oep-0016-bp-adopt-bootstrap.rst
oeps/oep-0019-bp-developer-documentation.rst
oeps/oep-0021-proc-deprecation.rst
oeps/oep-0023-style-customization.rst
oeps/oep-0026-arch-realtime-events.rst
oeps/oep-0026/caliper-realtime-events.rst
oeps/oep-0026/xapi-realtime-events.rst
oeps/oep-templates/adr-based-template.rst

This updates a number of URLs to use HTTPS where the server supports
it. It isn't a comprehensive update, just a few domains that show up a
lot in the docs:
- `edx.readthedocs.io`
- `open-edx-proposals.readthedocs.io`
- `github.com`
- `www.django-rest-framework.org`
- `docs.celeryproject.org`
- `http://thinkrelevance.com -> https://cognitect.com` (redirects)

chore: Change http URLs to https

---

oeps/oep-0037-bp-test-data.rst
oeps/oep-0037/decisions/0001-yaml-centralization.rst
oeps/oep-0037/decisions/0002-remote-dev-data-generation.rst
oeps/oep-0037/decisions/0003-data-creation-functions.rst

This is a first draft of an approach to consistently managing data sets that can be shared across unit tests and development environments to facilitate the development and testing of Open edX functionality.  I suspect we'll want better nomenclature for some of the ideas outlined here, but first I'd like to get some feedback on whether or not this is even the direction we want to go.  Feedback of any and all kinds are welcome!

OEP-37: Dev Data

---

.readthedocs.yaml

Adding configuration file for building documents by Read the Docs.
**For details**:
https://docs.readthedocs.io/en/stable/config-file/v2.html

BOM-2461: Add readthedocs.yaml

---

oeps/oep-0049-django-app-patterns.rst

This should have been done pre-merge, but was missed.

doc: Mark DJango app patterns OEP accepted

---

oeps/oep-0021-proc-deprecation.rst

We have found that the usage of Removal dates is
somewhat confusing and just duplicates the current functionality
of Accepted dates. We are removing them to help clarify the process.
We would also like to include links to Discourse threads in DEPR
tickets, because it makes it easier to cross reference the discussions.

fix: Updates to OEP-21: Deprecaton

---

oeps/oep-0017-bp-feature-toggles.rst

Adds additional links to the reference implementation of
OEP-17 for example reports and usages of toggle
annotations.

docs: add toggle reporting examples

---

oeps/oep-0018-bp-python-dependencies.rst

- Clarify recommendation on using `--rebuild` flag
- Update cookiecutters URL, since the cookie cutter repos were combined
- Use syntax highlighting for code blocks only where appropriate
- Remove reference to deprecated `owner` field from OEP-2
- Remove reference to dead site "allmychanges"

fix: Various OEP-18 clarifications and updates

---

oeps/oep-0050-hooks-extension-framework.rst

This PR converts the previous proposal held in a google doc to a formal OEP

OEP-50 | initial draft of the hooks extension framework

---

oeps/oep-0049-django-app-patterns.rst

Specifically, even if exporting celery tasks via the api.py file, you'll still want to reference the tasks.py name when routing.

docs: add warning about celery routing for oep 49

---

.github/workflows/upgrade-python-requirements.yml

**Issue:** [BOM-2555](https://openedx.atlassian.net/browse/BOM-2555)
- Requirements upgrade builds were [failing](https://github.com/edx/open-edx-proposals/runs/2662889664?check_suite_focus=true) due to Sphinx not being installed when running `make upgrade` in the script. 
- Install `sphinx` before running make upgrade to set the Sphinx build paths for the Make file.
- Ran the upgrade script with the upgraded `upgrade-python-requirements.yml` and [build](https://github.com/edx/open-edx-proposals/runs/2663098993?check_suite_focus=true) ran successfully and created the [PR](https://github.com/edx/open-edx-proposals/pull/219). The build errored out at the end when tagging the team for review which can be resolved by giving permission to `arbi-bom` team for this repo.

BOM-2555: Fix Requirements Upgrade Github Action

---

oeps/oep-0002-bp-repo-metadata.rst
oeps/oep-0014-proc-archive-repos.rst

When OEP 14 was first written, Github did not yet have a way to mark a
repository as "archived" (adding a banner to the web view of the repo
and makign it read-only). This made it more important for us to mark
the repo via other means, including changing the description, README,
and metadata.
Main changes:
- Mark ``archived`` as obsolete in OEP 2
- Remove requirement of changing repo description (but still request
explaining *why* it is being archived, what the replacement is, etc.)
Minor changes:
- Put archive step before move step
- Most valuable step first
- Easier to forget to do the archiving step if it gets moved first

docs: Update archive OEP to match current process

---

oeps/oep-0045/decisions/0001-tutor-as-replacement-for-edx-configuration.rst

This adds an ADR specifying what criteria any replacement for `edx/configuration` should meet, then proceeds to evaluate the Tutor project against them, finally proposing it as a suitable replacement once certain conditions are met.
[Forum thread](https://discuss.openedx.org/t/lets-talk-about-the-native-installation/3269)
[OEP-45](https://github.com/open-craft/open-edx-proposals/blob/master/oeps/oep-0045-arch-ops-and-config.rst)
[OEROADMAP-21](https://openedx.atlassian.net/browse/OEROADMAP-21)
[BTR-43](https://openedx.atlassian.net/browse/BTR-43)
[DEPR-122](https://openedx.atlassian.net/browse/DEPR-122)

OEP-45, ADR 1: Tutor as replacement for edx/configuration

---

.readthedocs.yaml
Makefile
README.rst
oeps/conf.py
oeps/oep-0001.rst
oeps/oep-0005-arch-containerize-devstack.rst
oeps/oep-0011-bp-FED-technology.rst
oeps/oep-0016-bp-adopt-bootstrap.rst
oeps/oep-0017-bp-feature-toggles.rst
oeps/oep-0019-bp-developer-documentation.rst
oeps/oep-0026-arch-realtime-events.rst
oeps/oep-0026/xapi-realtime-events.rst
oeps/oep-0041-arch-async-server-event-messaging.rst
oeps/oep-0045-arch-ops-and-config.rst
oeps/oep-0049-django-app-patterns.rst
oeps/oep-templates/adr-based-template.rst
oeps/oep-templates/external-link-template.rst
oeps/oep-templates/pep-based-template.rst

Doc warnings tend to indicate actual broken links, bad targets or
other useful information about how docs are broken.  They should be
treated as errors and fixed before merging new changes to master.

fix: Treat docs warnings as errors by default. 

---

Makefile
README.rst
oeps/best-practices/oep-0051-bp-conventional-commits.rst

* Document commitlint exceptions like "Revert", "squash! ", and "fixup! ".
* Also includes minor doc updates for local testing.
**Note:** This is replacing https://github.com/edx/open-edx-proposals/pull/254 with docs on existing exceptions.

docs: OEP-51: conventional commit linting exceptions 

---

README.rst

I'm working with a fresh environment and found I would repeatedly run into this error:
```
Warning, treated as error:
dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting
make: *** [html] Error 2
```
You must install GraphViz (because the warning errors out the build). I got assistance on this issue from https://github.com/IQSS/dataverse/pull/7230 and borrowed the language they used because I felt it was clear.

Update README to include GraphViz installation requirement

---

oeps/architectural-decisions/oep-0031-arch-i18n.rst

This PR fixes header indentation levels (following [the Sphinx guide](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections))
Note that currently, many sections are defined as top level pages, resulting in their inclusion in the lefthand sidebar of https://open-edx-proposals.readthedocs.io/en/latest/index.html
For this PR, I looked through numerous OEPs and followed the heading levels I saw in others.
I also changed `OEP-0031` to `OEP-31` within the doc, following what I see the vast majority of other OEPs doing.

fix: formatting fixes for OEP-31

---

oeps/architectural-decisions/oep-0014-proc-archive-repos.rst

As part of the edx -> openedx set of repo migrations, we've created a
new openedx-unsupported org to park archived repos going forward.

docs: update OEP-0014 to use openedx-unsupported

---

oeps/processes/oep-0001.rst

In the original doc, the process for getting an Arbitrator is to have one assigned by an internal edX team (I believe, at least - the wiki page linked to in the OEP is not publicly available). Moving forward, no one community member should have the ultimate authority in community decision making, not even tCRIL; I don't want tCRIL to just step in and take edX's place. Instead, I'd much rather a solution that allowed the whole community to participate in decision making, and this PR proposes a way for that to happen.
Additionally, I think it's reasonable to codify the fact that many of us are organically finding Arbiters due to us having domain expertise and knowing who in the community is out there working on the same or similar problems and would be good to arbitrate. Therefore I've …

[OEP-1] Community-based Decision Making for Arbiter Selection

---

oeps/architectural-decisions/oep-0014-proc-archive-repos.rst

Moving forward, we should make sure that OEPs contain procedures that are relevant to the whole community. When specific community members have practices that are relevant just to them, they should find a way to document those extra steps for their team.

[OEP-14] Change internal edX procedures to community-based ones

---

oeps/processes/oep-0054-core-contributors.rst

This document defines the Core Contributor (CC) Program, a program that grants rights to individuals
in the Open edX community that allow them to actively participate in defining and deciding the
direction of the platform.

OEP-54: Core Contributor Program

---

oeps/processes/oep-0054-core-contributors.rst

In https://github.com/openedx/open-edx-proposals/pull/275 it was pointed out right at the end of review that there was no caveat for removing Core Contributors. This presents a set of criteria for how that may happen.

OEP-54: Procedures for removing Core Contributors

---

oeps/processes/oep-0054-core-contributors.rst

This change specifies how multi-responsibility roles (such as coding CCs) go about expanding those rights. I propose this goes through the same process as adding a new CC, albeit shortening the review period to one week in many cases.

[OEP-54] Specify expansion of responsibilities

---

oeps/processes/oep-0054-core-contributors.rst

Our first Core Contributor nomination under OEP-54 guidelines was:
https://discuss.openedx.org/t/core-contributor-nomination-maria-grimaldi/6548
The clarifications in this commit are a result of feedback and
observations during this nomination process.

docs: clarify new CC member voting for OEP-54

---

oeps/architectural-decisions/oep-0049-django-app-patterns.rst

Fix the _name_ of the link to the doc file
Standardize the way the title is displayed to match other oeps

fix: fix doc link and standardize title display

---

oeps/processes/oep-0001.rst
oeps/processes/oep-templates/adr-based-template.rst
oeps/processes/oep-templates/external-link-template.rst
oeps/processes/oep-templates/pep-based-template.rst

Change history as a part of the OEP was added to OEP-1 in https://github.com/openedx/open-edx-proposals/pull/19 but this seems to have been removed from OEP-1 at some point. However, a good proportion of OEPs do have this section, and broadly I find these sections extremely useful. I propose we add them back in as part of the OEP template, and we make them even **more** useful by also adding links to PRs so readers can quickly access the full discussion / context around why a change was made.
See https://github.com/openedx/tcril-engineering/issues/132

OEP-1 Codify the Change History section for all OEPs

---

oeps/processes/oep-0001.rst

When I was first asked to be an Arbiter, I was a bit confused by this documentation - OEP-1's workflow is described from the POV of an Author, so information about what an Arbiter is and does is scattered throughout the doc. I think providing this short tl;dr within the top-level linked Arbiter section will clarify, at a glance, what the role is and better inform a community member if they wish to play this role.

OEP-1 Provide tl;dr of Arbiter role

---

oeps/processes/oep-0001.rst

As we've seen in existing Process OEPs, they are changed relatively frequently (look at the Changelog for OEP-1, for instanceAt the same time, OEP-1 states that processes are essentially set in stone, requiring a full new OEP to change them. I strongly disagree; process should always aim to be flexible, as lightweight as possible, and willing to change in the face of new requirements or needs of the people who use it.

In OEP-1, codify that Process OEPs can change

---

oeps/processes/oep-0001.rst

For the Best Practice updates, it's a bit hard to follow what steps you need to follow, and arbiters are required - even for small changes.
For Architecture updates, currently, the Arbiter needs to arbitrate all future changes, which locks to one person having control over an OEP. This doesn't scale as people move in and out of the community, and also doesn't seem to be how we're currently operating.
This PR updates OEP-1 for clarity, for reflection of how we currently actually handles OEPs, and defers to a more community based procedure.
See https://github.com/openedx/tcril-engineering/issues/134

OEP-1 Clarify OEP update procedures

---

oeps/processes/oep-0001.rst

In the first sections of OEP-1, it is not stated that an Author 'owns' an OEP or what the definition of 'ownership' is. However, in the sections under OEP Maintenance, it is stated that the Authors do own the OEP, and if the Author is not available, it seems the Arbiter does. However, given our Community is currently largely-defined by employment-based membership, it can, will, and is the case that [some OEPs](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0016-bp-adopt-bootstrap.html) have Authors and Arbiters that are no longer community members.
Since 'ownership' of an OEP is not defined, I propose that we migrate to a 'stewardship' model. For now,  I propose that the Architecture Group (defined in the OEP) are stewards of the OEP; as we build an Architecture …

[OEP-1] Switch author-ownership model to a community-stewardship one

---

oeps/processes/oep-0054-core-contributors.rst

Follow-up to the discussion in https://github.com/openedx/open-edx-proposals/pull/292/files#r800459077 about handling fulfillment of commitments by core contributors.
@sarina Here is a proposed change, to tie the commitments to the responsibilities of a core contributor, and make it explicit that it is expected to be upheld, to maintain the core contributor title. It however provides plenty of room for adapting to each individual situation -- the important imho is to notice those situations and discuss them.

 OEP-54 - Handle commitments fullfilment 

---

oeps/processes/oep-0056-architectural-advisory-process.rst

Tweaks to the .rst syntax to keep long URLs from interrupting the text.

refactor: OEP-56: use shorter-form links to keep the text more readable.

---

oeps/processes/oep-0056-proc-architectural-advisory-process.rst

Was missing a heading on the latest date in the changelog.

docs: fix OEP-56 changelog formatting

---

oeps/processes/oep-0001.rst

The Architecture Group is a backstop; they should help with Arbiter selection when requested, but it is not required to include them.
Clarify that currently the "Architecture Group" is the collection of members of the `#architecture` Slack channel.

docs: Clarify what is meant by Architecture Group and what they do

---

oeps/processes/oep-0055-proc-project-maintainers.rst
oeps/processes/oep-0055/decisions/0001-use-backstage-to-support-maintainers.rst

Since this is the first ADR under oep-55 I also added the relevant
directory structure and wired it up into the OEP rst.

docs: Add an ADR for using Backstage to support OEP-55

---

oeps/architectural-decisions/oep-0041-arch-async-server-event-messaging.rst
oeps/architectural-decisions/oep-0052-arch-event-bus-architecture.rst

OEP that makes the case for adding an event bus, as well as a variety of other decisions around implementing an event bus.
**Notes:** 
1. This PR replaces https://github.com/openedx/open-edx-proposals/pull/233. The original OEP primarily discussed the implementation technology, which was moved to a separate ADR. See the OEP's 
"Change History" for more details of what has changed.
2. The goal is to merge this OEP with a Provisional status, and continue our implementation and learning before moving this to Accepted.

OEP-52: docs: add OEP for event bus architecture (ends June 30)

---

oeps/architectural-decisions/oep-0014-proc-archive-repos.rst
oeps/processes/oep-0001.rst
oeps/processes/oep-0021-proc-deprecation.rst
oeps/processes/oep-0054-core-contributors.rst

Point to the openedx.org shortcut which we can update as needed.

fix: Update the slack invite link.

---

oeps/architectural-decisions/oep-0052-arch-event-bus-architecture.rst

1. Fixed the header to match other OEPs, using OEP-XX
in place of OEP-00XX.
2. Fixed the status to just read "Provisional".
3. Fixed the language of the note about future updates,
since this is no longer a draft under review.
Note: changes were minor enough I did not update the change history or modified date.

fix: OEP-52 provisional notes

---

oeps/processes/oep-0054-core-contributors.rst

Per discussion on https://discuss.openedx.org/t/core-contributor-nomination-miguel-and-mikel-amigot/7749/21 it seems some points of the nomination process are not clear enough.
Reviewers... perhaps @pomegranited @antoviaque @feanil ?

fix: clarify CC noms require evidence of past contributions

---

oeps/processes/oep-0021-proc-deprecation.rst

This PR adds a side note to the deprecation status accepted, so it suggests adding an explanation ADR when contributions use the deprecated feature. 
See thread https://openedx.slack.com/archives/CGB0S3L12/p1655937179658019

docs: update OEP-21 with note on new usages of depr features

---

oeps/architectural-decisions/oep-0052-arch-event-bus-architecture.rst

Also adjust link text to match ADR title.
See https://github.com/openedx/event-bus-kafka/issues/2

fix: Update URLs for moved event-bus-kafka ADRs

---

oeps/processes/oep-0055/decisions/0002-maintainership-transfer-process.rst

There's lots of cleanup to do still but this outlines the process by
which we can find new maintainers for components and what to do if we
can't.

docs: Add a proposed process for transferring maintainership.

---

oeps/best-practices/oep-0019-bp-developer-documentation.rst
oeps/processes/oep-0001.rst
oeps/processes/oep-0055-proc-project-maintainers.rst
oeps/processes/oep-0055/decisions/0003-readme-specification.rst

This is an additional ADR for OEP-55 which provides details about the
README specification.

docs: Add an ADR the format of README files in repos.

---

oeps/processes/oep-0055/decisions/0001-use-backstage-to-support-maintainers.rst

Every catalog-info.yaml file should include a header comment with a link to the OEP, so that spelunkers in repos can understand the purpose of the file.

docs: add a header to the sample catalog-info.yaml file

---

oeps/best-practices/oep-0051-bp-conventional-commits.rst

Just updating the metadata for the Private-ref change.

docs(oep-51): private-ref footer change wasn't logged

---

oeps/architectural-decisions/oep-0014-proc-archive-repos.rst

* Reversed order of "Change History".
* Remove example using older edX GitHub orgs to better clarify that this OEP only covers openedx org repos.

docs: update archive repo OEP for 2U

---

oeps/best-practices/oep-0019-bp-developer-documentation.rst

- Fix heading
- Use `1.` title instead of `0001`, since I think the former is more common (and readable)

docs: Small tweaks to ADR template

---

oeps/index.rst

The published pages had duplicate "headings" on the home page:
and also linked to three empty or non-existent index pages at the bottom.  This pull request cleans that up.

refactor: no need for double headings, or empty index pages

---

oeps/best-practices/oep-0051-bp-conventional-commits.rst

This updates guidance for single targeted dependency upgrades to use the more specific "feat" or "fix" labels as appropriate. There is no reason to hide the meaning behind "chore" in this case.

docs: update OEP-51 guidance for chore

---

oeps/architectural-decisions/oep-0023-style-customization.rst
oeps/architectural-decisions/oep-0048-brand-customization.rst

OEP-48 deals with customising branding for MFEs usin an npm package override.
This mechanism for branding is now supported across all MFEs, and is also
supported by both the configuration repo, and Tutor. As such this PR updates its
status from Provisional to Accepted.

docs: Mark OEP-48 as Approved and OEP-23 as replaced

---

oeps/best-practices/oep-0019-bp-developer-documentation.rst

The edx-developer-docs repo is being deprecated, but we call it out as a
part of OEP-19.  This change updates OEP-19 to replace the dev docs repo
with the developer section of the new docs.openedx.org site/repo.

docs: Update OEP-19 given dev-docs deprecation.

---

oeps/processes/oep-0060-proc-sec-group.rst

Make it so we announce on discourse to everyone when there will be a
security update coming instead of just to the security-notifications
mailing list.  Given that it's pretty easy to get on the
security-notifications mailing list, this doesn't make things less
secure (django and other major projects use the approach we're moving
to).

docs: Update the security announcement process

---

oeps/architectural-decisions/oep-0052-arch-event-bus-architecture.rst

Update OEP-52 to better reflect the current state of the event bus project.

docs: update oep 52 (event bus architecture)

---

oeps/index.rst

On our OEP homepage there's a note about  which also have the acronym OEP. However, the page listed (oep.readthedocs.io) hasn't been updated since 2016. Thus I believe there is not an appetite for people looking for OER Enhancement Proposals, and it seems a little silly for us to provide a redirect. Googling OEP yields tons of different acronyms, most commonly is Open Enrollment Period for US Healthcare. Anyway. @feanil ?

Remove note about OER Enchancement Proposals

---

oeps/processes/oep-0060-proc-sec-group.rst

The SWG member is on duty, not on call. The purpose of the rotation is not to have someone available in the middle of the night; volunteers of the SWG should not have to expect to work after their normal working hours.

fix: OEP-60: s/on-call/on-duty

---

README.rst
oeps/index.rst

Updates the README file to comply with OEP-55: https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055/decisions/0003-readme-specification.html. I also noticed that the language defining OEPs casts them as purely technical decisions. However, with OEPs such as Core Contributors and Core Product, I think we've found that OEPs are transcending pure technical decisions. I've added the language of 'community decisions' to address this. @feanil and anyone else welcome.
Review open until Mon 13 Feb

Update README and tweak OEP language

---

oeps/processes/oep-0054-core-contributors.rst

This update to OEP-54 adds a link to the reference definition of what is being considered "core contributor work", which will live in the wiki. 
The corresponding review can be found in the forum at https://discuss.openedx.org/t/final-review-core-contributors-work-scope/8821

OEP-54 - Core Contributors - Define work scope

---

oeps/processes/oep-0010-proc-openedx-releases.rst

We used to support different installation methods when the release
process was first defined, remove mentions of the old methods and link
to the current methods.

docs: Remove old information about installation methods.

---

oeps/processes/oep-0010-proc-openedx-releases.rst

Remove a line about edx.org release from the motivation of Open edX releases.

docs: Fix mentions of edx.org

---

oeps/best-practices/oep-0049-django-app-patterns.rst

This is just to try force a readthedocs build, but that sentence could use a period for consistency anyway.

fix: add punctuation in OEP-49

---

oeps/best-practices/oep-0018-bp-python-dependencies.rst

Nine different URL-specified Python dependencies had accumulated in edx-platform, noticably increasing the amount time it took to install edx-platform requirements.
After many developer hours of work, we are nearly finished converting them to PyPI-hosted depencencies:
https://github.com/openedx/wg-developer-experience/issues/153
We make these OEP updates in order to clarify that URL dependencies should not be added except in the two specified circumstances and that the follow-up work of moving them to PyPI must be recorded.
Direct link to rendered RST: https://github.com/kdmccormick/open-edx-proposals/blob/kdmccormick/url-dependency-clarifications/oeps/best-practices/oep-0018-bp-python-dependencies.rst
edx-platform PR to update CODEOWNERS and the github.in comment: …

docs: tighten OEP-18 rules on URLs for Python dependencies

---

oeps/processes/oep-0054-core-contributors.rst

As discussed [in this thread](https://github.com/openedx/openedx-k8s-harmony/issues/9#issuecomment-1354032983) back in December, I want to propose a simpler way to nominate several existing CCs to get commit rights to a newly created repo.

Tweak to OEP-54: streamline the process for adding CCs to a new repo

---

oeps/best-practices/oep-0013.rst

Updating the link for the wiki area for the Rest Best Practices.

fix: updating a broken link

---

oeps/best-practices/oep-0049-django-app-patterns.rst

We [now](https://github.com/openedx/edx-platform/pull/31903) have a tool for enforcing OEP-49 compliant usage of `api.py` for Django apps. This updates the OEP to raise awareness of the new linter and encourage broader usage.

Mention import linter for api.py in OEP-49

---

oeps/best-practices/oep-0049-django-app-patterns.rst

In [OEP-49](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0049-django-app-patterns.html#data-py), it gives this example of how to use [`attrs`](https://www.attrs.org/en/stable/) in data.py:
```python
from enum import Enum
import attr
def ProgramStatus(Enum):
ACTIVE = "active"
RETIRED = "retired"
@attr.attrs(frozen=True)
class ProgramData:
uuid: str = attr.attrib(
validator=[attr.validators.instance_of(str)]
)
title: str = attr.attrib(
validator=[attr.validators.instance_of(str)]
)
status: str = attr.attrib(
validator=[
attr.validators.instance_of(str),
attr.validators.in_(ProgramStatus)
]
)
```
There are two problems with this:
1. It should not be using `def` but rather `class` to define the enum. As shown, the declaration is accepted but the enum won't work.
2. …

Fix examples of enumerations and attrs in OEP-49 App Patterns: data.py

---

oeps/processes/oep-0021-proc-deprecation.rst

Deprecation can result in others taking responsibility, make that
more clear in the process documentation.

docs: Show that others can take responsibility.

---

oeps/best-practices/oep-0019-bp-developer-documentation.rst

Minor update to the ADR template in OEP-19, providing a specific example for status. The new example provides a date format, and also removes the bullet that may be used if copying from the list of examples of status.

docs: [OEP-19] update status example in ADR template

---

oeps/architectural-decisions/oep-0052-arch-event-bus-architecture.rst

Adds a reference to a new ADR in openedx-events about allowing multiple event types per topic

docs: add new ADR reference to OEP52

---

oeps/best-practices/oep-0018-bp-python-dependencies.rst

* Update the standard name for CI requirements files and remove references to Travis CI now that we've switched to GitHub Actions
* Add more clarification about what typically goes into a CI requirements file

[docs] Remove Travis CI references, rename and clarify CI file

---

oeps/processes/oep-0014-proc-archive-repos.rst
oeps/redirects.txt

After archiving a repo, all issues become read-only. This is not ideal for DEPR tickets, so the DEPR issue should be transferred out before archiving. This step is now detailed in OEP-14.
Also fixes the directory that OEP-14 is in.

docs: OEP-14 update for DEPR transfer when archiving

---

oeps/processes/oep-0021-proc-deprecation.rst

Updates the Discourse template with notes on how to follow the removal status of a DEPR ticket.

docs: OEP-21 update for how-to follow DEPR removal status

---

oeps/architectural-decisions/oep-0064-arch-mobile-application-codebase-modernization.rst

Opening this OEP draft for community review and input. 
**Abstract**
As part of the discovery effort done for a funded contribution (FC-0011) we are recommending that the Open edX platform adopt newly built iOS and Android applications as the new default mobile applications for the platform moving forward, starting with the next named release. These new applications are rebuilt with MVVM architectural patterns and are fully rebuilt in Swift and Kotlin respectively. These new code bases should facilitate faster development cycles, improved pluggability and community contribution rates. Currently not all functionality is 100% identical to the existing mobile applications, but efforts are underway to improve pluggability and close common community requirements for the mobile experience.
The …

OEP-64 Mobile Application Codebase Modernization 

---

oeps/architectural-decisions/oep-0064-arch-mobile-application-codebase-modernization.rst

OEP status changed to Approved and bullet formatting updates
Will remove draft state once formatting updates are confirmed

style: OEP status changed to Approved and bullet formatting updates

---

oeps/best-practices/oep-0011-bp-FED-technology.rst
oeps/best-practices/oep-0011/decisions/0001-react.rst
oeps/best-practices/oep-0011/decisions/0002-redux.rst
oeps/best-practices/oep-0011/decisions/0003-jest-rtl.rst
oeps/best-practices/oep-0011/decisions/0004-js-ecma.rst
oeps/best-practices/oep-0011/decisions/0005-django-templates.rst

This PR does not change OEP-11 or the decisions made within, it simply reorganizes them into ADRs. This will allow us to better reference individual decisions as we discuss future changes and write new ADRs.
For example: we will be able to reference `OEP-11/ADR-4` when discussing the use of TypeScript, or `OEP-11/ADR-2` when discussing Providence ([1](https://opencraft.com/better-state-management-for-react-using-providence/), [2](https://eye-of-providence.readthedocs.io/en/latest/index.html)) or [React Context](https://react.dev/learn/passing-data-deeply-with-context
).

OEP-11: move rejected alternatives into ADR pages

---

oeps/processes/oep-0055/decisions/0004-release-data-in-catalog-info-files.rst

We want to be able to tell when no decision has been made on a
repository with regeard to release tagging.

docs: Update catalog-info.yaml release annotation.

---

oeps/processes/oep-0055/decisions/0003-readme-specification.rst

See https://github.com/openedx/edx-cookiecutters/issues/396 -- we'd like to centralize this information rather than templating it to every repo's README.

docs: Suggest linking to the developer how-to docs rather than inlining

---

oeps/processes/oep-0054-core-contributors.rst

The link between sections 4 and 6 could be still clearer and definitively establish that votes for new CCs must come from current CCs.

fix: clarifiying who votes.

---

oeps/processes/oep-0054-core-contributors.rst

You can't have different number of columns in different rows of a
list-table.

docs: Fix an error that slipped through CI.

---

oeps/processes/oep-0055-proc-project-maintainers.rst
oeps/processes/oep-0055/decisions/0001-use-backstage-to-support-maintainers.rst

(also some spelling in the main OEP.)

fix: catalog-info.yaml name should be the repo name

---

oeps/best-practices/oep-0066-bp-authorization.rst

This will add a link to important information about the status of the new proposed service. This ensures the OEP will have up to date information about the project without requiring regular OEP updates.

OEP-66 - Add clarification note to course_roles_role section

---

oeps/processes/oep-0055/decisions/0005-managing-core-contributors.rst

This ADR clarifies the rights and responsibilities of Maintainers with respect to the Core Contributors.
Much of this interaction was previously inferred, but as it was not spelled out, there has been some confusion with respect to how much control Maintainers have over Core Contributors. In short, Maintainers do not control Core Contributors; CCs have passed a nomination process and have gained the support of the community to make good decisions in the repository. However, Maintainers are allowed to know who has CC rights on their repo, communicate repo standards and architectural vision to them, and initiate CC remove procedures if a CC is not following community standards and is unresponsive to feedback.
Relevant parts of OEP-54 Core Contributors & OEP-55 Maintainers are cited within …

OEP-55:ADR-5 Clarify Maintainer Interaction with Core Contributors

---

oeps/processes/oep-0054-core-contributors.rst

- @feanil and I updated the Core Contributor wiki page tree today, so we are removing now-outdated links and streamlining this a bit
- I keep wanting to link to the "3 C's" but I can't easily because I can only link to https://docs.openedx.org/projects/openedx-proposals/en/latest/processes/oep-0054-core-contributors.html#adding-new-core-contributors and then you have to read to paragraph 2 to find the 3C's. This will make my life easier and I hope yours too.

docs: Adjust links and add 3Cs appendix to OEP-54

---

.gitignore
oeps/processes/oep-0021-proc-deprecation.rst

These proposed changes from the deprecation working group are around making sure that every accepted deprecation ticket has an owner responsible for shepherding it through the process.

feat: proposed changes from the DEPR WG

---

oeps/conf.py
oeps/processes/oep-0057/README.rst

We authored these in LucidChart and while that text is contained within the OEP, it feels even better to put that info directly where someone looking at the diagram source would want to know about it.

Add README for OEP-57 diagram sources

---

oeps/architectural-decisions/oep-0045-arch-ops-and-config.rst
oeps/processes/oep-0001.rst

Over time, some OEPs may stay relevant - for example, they may have many
sections or core ideas that are still relevant to the project - while containing
many details that have become stale over time. When we are in agreement that the
OEP needs updating, we use this status to indicate to those browsing the OEPs
that this particular one requires some renewed attention.
When changing status to "Needs Revision", a row titled "Revision Ticket" should
be added to the preamble (directly under the status field) that directs to the
GitHub issue or draft pull request in the ``open-edx-proposals`` repository that
describes what about the OEP that needs revisioning.
An example is added with OEP-45. OEP-45 is directionally correct and we shouldn't mark it as _obsolete_ - it contains many great ideas. …

Add a Needs Revision status for OEPs

---

oep-templates/adr-based-template.rst
oep-templates/external-link-template.rst
oep-templates/pep-based-template.rst
oeps/processes/oep-0001.rst

Follows up on #597 - finishes removing remaining references in OEP-1 and in templates

docs: Remove remaining references to 'Withdrawn' state in OEP-1

---

oeps/processes/oep-0055/decisions/0001-use-backstage-to-support-maintainers.rst

docs: catalog-info.yaml should primarily use "Web" for icon

---

oeps/architectural-decisions/oep-0052-arch-event-bus-architecture.rst

Addresses #415
Will squash & fix linting issue before merging

docs: Remove OEP-52 note about provisional status, as it has been accepted.

---

oep-templates/adr-based-template.rst
oep-templates/external-link-template.rst
oep-templates/pep-based-template.rst
oeps/processes/oep-0001.rst

Reflect reality that rejected proposals are frequently left unmerged even though OEP-1 had previously called for it.
Remove the unused "Rejected" state and codify that you should just close the PR, and leave a note as to why.
Addresses #428

Remove "Rejected" OEP status, and indicate they should be left unmerged

---

oeps/processes/oep-0001.rst

Previously, OEP-1 didn't have a clear process for announcing merges,
which is especially important for OEP updates that didn't necessarily
go through a wider review.
Addresses issue #493

docs: OEP-1: Add a section on announcing changes

---

oeps/architectural-decisions/oep-0065-arch-frontend-composability.rst

This PR adds another rejected alternative to OEP-65.  We investigated using Vite for module federation and found it wasn't a viable alternative to Webpack module federation.

docs: Adding a rejected alternative to OEP-65 for Vite module federation

---

.github/workflows/upgrade-python-requirements.yml

Currently, Arbi-BOM is being tagged on upgrade PRs but this repo is owned by Sarina as per the catalog-info.yml file, so updating github actions to tag Sarina instead.

build: tag correct owner for review on uprgade PRs

---

oeps/best-practices/oep-0067-bp-tools-and-technology.rst
oeps/best-practices/oep-0067/decisions/frontend/0002-redux.rst
oeps/best-practices/oep-0067/decisions/frontend/0010-react-query.rst

* Changed guidance on React state/data loading to recommend React Query instead of Redux
* Updated JavaScript/TypeScript guidance
Previous discussions etc:
* https://openedx.atlassian.net/wiki/spaces/BPL/pages/3852632086/Typescript+and+React-Query+for+api+usage.
* https://openedx.atlassian.net/wiki/spaces/AC/pages/3791290378/tanstack+react-query+An+overview
* My conference [lightning talk on React Query](https://docs.google.com/presentation/d/19AIPaRDJkOMLnCn-7BapHNLpS1Hz9Pti9Rz-apI5ZVY/edit)
Preview this at https://open-edx-proposals--616.org.readthedocs.build/en/616/best-practices/oep-0067-bp-tools-and-technology.html

docs: ADR to use React Query instead of Redux, update general JS/TS guidance

---

oeps/architectural-decisions/oep-0065-arch-frontend-composability.rst
oeps/architectural-decisions/oep-0065/decisions/0001-unified-platform-repository.rst

This ADR describes a decision to create a unified platform library, combining frontend-build, frontend-platform, frontend-plugin-framework, frontend-component-header, frontend-component-footer, and eslint-config.  It will also include the ‘shell’ application for the new architecture proposed in OEP-65.

docs: adding an ADR to OEP-65 about a unified platform repository

---

oeps/best-practices/oep-0067-bp-tools-and-technology.rst

Per a discussion with @regisb about how we can speed up MFE build times in Tutor, I want to clarify how `dependencies` and `devDependencies` should be used. The goal is that tutor can install MFE dependencies using `npm ci --production` which would do a fast install that excludes `devDependencies`. This will be a significant speedup in the case where we can exclude things like Jest (which is a very large and bloated package[^1]) that aren't needed just to build and deploy the MFE.
Note: this is very much _not_ the case now:
* `frontend-build` [includes](https://github.com/openedx/frontend-build/blob/ae8ce98d5252d9ddd4e730d6b21ca40257453bef/package.json) Jest, eslint, TypeScript, react-dev-utils, and more in `dependencies`, and puts `@babel/preset-typescript` which I think is required for …

Clarify how devDependencies should be used for NPM packages (OEP-67: Standard Tools and Technologies)

---

oeps/conf.py

See https://about.readthedocs.com/blog/2024/07/addons-by-default/ for details but
essentially RTD is changing how it's building docs and this will let us handle the
change gracefully.

build: Manually pull some RTD Context.

---

oeps/processes/oep-0054-core-contributors.rst

Moving forward, the Axim team will engage in annual audits of individual Core Contributors as well as organizational commitments to the Core Contributor Program. These edits describe when these audits will take place. 
Please provide feedback by 18 September.

docs: Describe annual renewal process for CC commitment

---

oeps/architectural-decisions/oep-0041-arch-async-server-event-messaging.rst
oeps/architectural-decisions/oep-0050-hooks-extension-framework.rst
oeps/architectural-decisions/oep-0052-arch-event-bus-architecture.rst
oeps/conf.py

This PR adds notes about Open edX Events and Filters to event-driven-related OEPs and the Hooks Extension Framework OEP, specifying where to find architectural decisions about the framework. This PR addresses: https://github.com/openedx/openedx-events/pull/438#pullrequestreview-2546953891

docs: [FC-0074] add note about decisions documented in each hooks repositories

---

oeps/architectural-decisions/oep-0030-arch-pii-markup-and-auditing.rst

OEP-30 has been largely implemented for several years, and so is being marked as accepted. Other changes are introduced to clarify the current state and replace references to legal teams with Axim Engineering, who can refer to Axim Legal if necessary.
Closes: #670

docs: Mark OEP-30 accepted and update

---

oeps/best-practices/oep-0067-bp-tools-and-technology.rst

Noticed some outdated notes in OEP-67 this morning and taking an opportunity to clean it up a bit.
[Build output](https://docsopenedxorg--666.org.readthedocs.build/projects/openedx-proposals/en/666/best-practices/oep-0067-bp-tools-and-technology.html)

Update OEP-67 to remove outdated author notes and update edX language

---

oeps/architectural-decisions/oep-0026-arch-realtime-events.rst
oeps/architectural-decisions/oep-0026/caliper-realtime-events.rst
oeps/architectural-decisions/oep-0026/xapi-realtime-events.rst
oeps/architectural-decisions/oep-0030-arch-pii-markup-and-auditing.rst
oeps/architectural-decisions/oep-0052-arch-event-bus-architecture.rst

This OEP has been accepted and largely implemented for a long time. This brings the OEP up to date with current reality.
Closes: #673

docs: Mark OEP-26 accepted, update

---

oeps/architectural-decisions/oep-0026-arch-realtime-events.rst
oeps/architectural-decisions/oep-0031-arch-i18n.rst
oeps/archived/oep-0006-arch-context-xblock-fields.rst
oeps/archived/oep-0016-bp-adopt-bootstrap.rst
oeps/best-practices/oep-0017-bp-feature-toggles.rst
oeps/best-practices/oep-0037-bp-test-data.rst

Convert links from edx.readthedocs.io to links on docs.openedx.org
The installing & configuring guide is not yet moved, so those links are currently unchanged. Ref https://github.com/openedx/docs.openedx.org/issues/830
In draft until I figure out what to do with ~~the link to the devdata guide in OEP-26, and~~ the toggles guide in OEP-17

docs: Update edx.rtd.io links to their docs.openedx.org equivalents

---

oeps/best-practices/oep-0067-bp-tools-and-technology.rst

I'm trying out doing a :ref: link from an intersphinx mapping in the docs.openedx.org repo.
This ref is needed to change the direct ref to OEP-67 in https://raw.githubusercontent.com/openedx/docs.openedx.org/068b045582075feaee7b07ed72d2ab39bd08ad1a/source/developers/references/developer_guide/conventions/frontend.rst to a relative :ref: link using a cross-reference role (https://docs.readthedocs.com/platform/stable/guides/intersphinx.html#using-intersphinx)
IDK I am hoping it works :)

build: Add ref for Sphinx cross-linking

---

oeps/best-practices/oep-0067-bp-tools-and-technology.rst
oeps/best-practices/oep-0067/decisions/frontend/0009-renovate.rst
oeps/best-practices/oep-0067/decisions/frontend/0011-caret-ranges-dependencies.rst

Adds an ADR under OEP-67 "Frontend Technology Selection"'s best practices to codify the (updated) recommendation to no longer pin dependencies in `package.json`, in favor of using caret ranges.
* OEP-67 ([preview](https://open-edx-proposals--687.org.readthedocs.build/en/687/best-practices/oep-0067-bp-tools-and-technology.html#frontend-technology-selection))
* ADR for using caret ranges in dependency versions ([preview](https://open-edx-proposals--687.org.readthedocs.build/en/687/best-practices/oep-0067/decisions/frontend/0011-caret-ranges-dependencies.html))

docs: add ADR about using caret ranges for npm deps

---

oeps/best-practices/oep-0051-bp-conventional-commits.rst
oeps/best-practices/oep-0067-bp-tools-and-technology.rst
oeps/processes/oep-0054-core-contributors.rst

Resolves #705, #681.
- fix and update links in OEP 51 and 67
- use :doc: roles for links to other Open edX documentation rather than hard links in OEP-67
- remove exception for eslint config for es5 in OEP-67
- fix typo in OEP-54
- reword the importance of descriptive commit bodies in OEP-51
OEPs touched:
- [OEP-51: Conventional Commits](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html)
- [OEP 54 Core Contributors](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0054-core-contributors.html)
- [OEP-67: Standard Tools and Technologies](https://docs.openedx.org/projects/openedx-proposals/en/latest/best-practices/oep-0067-bp-tools-and-technology.html#)

docs: small fixes and improvements for OEP 51, 54, and 67

---

oeps/best-practices/oep-0019-bp-developer-documentation.rst
oeps/best-practices/oep-0042-bp-authentication.rst
oeps/index.rst

So we can cross-reference within intersphinx docs

chore: Add cross-references to the OEP index page

---

oeps/architectural-decisions/oep-0041-arch-async-server-event-messaging.rst
oeps/architectural-decisions/oep-0050-hooks-extension-framework.rst
oeps/architectural-decisions/oep-0052-arch-event-bus-architecture.rst

Depends on
https://github.com/openedx/openedx-filters/pull/294
https://github.com/openedx/openedx-events/pull/505

chore: Update Events and Filters crossreferences to use `:ref:` rather than `:doc:`

---

oeps/best-practices/oep-0066/Open_edX_Auth_Overview_Table.rst

Adding cross-references to the docs, rather than referencing the HTML page directly, allows us to have more robust cross linking that is safe from filename/path changes (ofc provided no one changes the name of the ref!)

docs: Add crossreference for docs linking
