- oep-template.rst
- oeps/oep-0001.rst
@cpennington please feel free to reject any of these suggestions. I did have a few questions for you, marked "Cale" as comments.
> Copy edit suggestions and questions

- Makefile
- dev-requirements.txt
> Add a make target for running local development

- README.rst
> Add a README for github

- oeps/oep-0002.rst
@nedbat, @efagin: This adds definitions for a few of the keys that we are using in the `openedx.yaml` files.
> Add definitions for a few more standard OEP-2 keys

- oep-template.rst
- oeps/oep-0001.rst
- oeps/oep-0003.rst
- oeps/oep-0004.rst
- oeps/oep-0005.rst
> Add a Change History section to OEP-1

- Makefile
> Fix the no-sphinx case in the Makefile

- oeps/oep-0009.rst
Presenting an outline of proposed best practices for implementing and using permission checks in Open edX Python code.  Mostly reuses existing APIs and packages, although there is one noted gap for implementing queryset filtering with rule-based permissions.  A rough sketch of a proposed package to fill that gap is provided, although custom model manager methods and Django REST Framework filter classes can be used in the meantime.
> OEP-9: User Authorization (Permissions)

- oeps/oep-0001.rst
@cpennington @jbarciauskas @efagin -- just some readability/formatting edits -- if I understand correctly, these changes are within the boundaries of updating the existing OEP-1 vs. submitting a new OEP to replace it.
> Improve readability of roles descriptions

- oeps/oep-0001.rst
This level of formality seems silly for this type of fix... but I figured it was better than just committing directly to master.
> Fix typo in OEP-1

- oeps/oep-0002.rst
> Fix date in OEP-2 changelog

- oeps/oep-0014.rst
This is a continuation of discussions that began in https://openedx.atlassian.net/wiki/display/IT/Proposed+Github+Deprecation+Process.
Please review @e0d @efagin @pmitros @wesmason @robrap 
Also let me know if you would be willing to serve as Arbiter of this OEP.
FYI @staubina @jlajoie @gsong @andy-armstrong @jibsheet
> OEP-14: Proposed process for archiving edX Github repositories

- oeps/oep-0002.rst
Related to OEP-14, #37.
Please review @cpennington @jibsheet @pmitros (I don't know how many people I actually need...).
> Change "obsolete" to "archived"

- oeps/oep-0011.rst
https://openedx.atlassian.net/browse/FEDX-273
This is an early draft of an OEP for front end best practices.
You can view the proposal in rendered form here:
https://github.com/edx/open-edx-proposals/blob/andya/front-end-best-practices/oeps/oep-0011.rst
FYI @AlasdairSwan @alisan617 @bjacobel @cahrens @dsjen
> OEP-11: front end best practices

- oeps/oep-0014.rst
@efagin @cahrens @jibsheet 
PTAL as per our previous discussions.
> Include forks in oep-14.

- oeps/oep-0024-bp-rate-limiting.rst
RST is a pain. Apparently I need to indent with 2 spaces and put new lines between the bullets to get it to render properly.
> Try again to fix nested bullets

- oeps/oep-0010-proc-openedx-releases.rst
Who should review this? Do we need to change the arbiter?
@nasthagiri @jmbowman ?
> Minor updates to match Hawthorn reality

- oeps/oep-0025-proc-incremental-improvements.rst
A proposed process for tackling large code changes which can be nicely parallelized by splitting the work into small pieces that can be worked on by developers throughout the Open edX community.  Feedback from that community is very welcome!  We want to make sure this works for people and actually facilitates more rapid progress on major objectives which have been moving somewhat slowly to date.
> OEP-25: Incremental Improvements

- oeps/oep-0021-proc-deprecation.rst
Based on recent breakage of the system due to removal of deprecated code, add a suggestion recommending a quick, simple codebase-wide impact analysis via GIthub's org+code search feature.
> OEP-21: Recommend codebase impact review.

- oeps/oep-0030-arch-pii-markup-and-auditing.rst
- Match reference implementation
- Include links to reference implementation
- Break the Organization tool out
- A couple of other small fixes
> Update OEP-30 to current understanding

- oeps/oep-0007-bp-migrate-to-python3.rst
Making some updates to reflect recent decisions and other changes since this was originally written:
* Clarified end of support dates
* Removed references to `future`, as we have generally preferred `six` and the document really suffers from trying to explain both and make the reader understand which to choose in a given case.  There is also now better tooling to automatically update code using `six` to use idiomatic Python 3 code instead.
* Similarly, recommend `python-modernize` instead of `futurize` for automated code conversion
* The wiki page mentioned in the original version was ultimately archived without being updated much; requires.io makes it much easier to track compatibility of dependencies with Python 3
* Mention the new Confluence page for tracking progress on updating …
> Update OEP-7 to reflect recent decisions

- oeps/oep-0018-bp-python-dependencies.rst
Made a few edits to reflect things we've learned in the last few months.
> Update OEP-18 to reflect recent experience

- oeps/oep-0014-proc-archive-repos.rst
@feanil I forget if there was another detail we wanted to add to this.
> Update openedx.yaml when archiving

- oeps/oep-0002-bp-repo-metadata.rst
This PR simply reformats OEP-2 according to the latest standards.  There are no content changes included.
> OEP-2: Formatting Updates

- oeps/oep-0019-bp-developer-documentation.rst
* "maintenance"
* "GitHub"
* The decisions folder is called decisions, not "local decisions"
> OEP-19 Dev Docs: Spelling and minor fixes

- oeps/oep-0004-arch-oauth-scopes.rst
adjust formatting to be more compatible with OEP-19 on developer
documentation.
> oep-19 compatible formatting

- oeps/oep-0014-proc-archive-repos.rst
Choose one of the previously rejected alternatives now that
we have some more experience with the impact of our choice.
> Update repo archival process.

- oeps/oep-0004-arch-oauth-scopes.rst
Add documentation of the scopes and filters and relevant ADRs added to Open edX.
**Note:** This PR is not meant to be a comprehensive update to OEP-4.
> Update OEP-4: Scopes: add current scopes and filters

- oeps/oep-0038-Data-Modeling.rst
A guide to data modeling at edX
> OEP-38 Data Modeling

- oeps/oep-0002-bp-repo-metadata.rst
Also tidied up some wording and references.
> OEP-2: Move "nick" to Obsolete.

- oeps/oep-0025-proc-incremental-improvements.rst
Looking for reviews/feedback on the TL;DR section added at the beginning!
> Updates to oep-0025-proc-incremental-improvements.rst

- oeps/oep-0021-proc-deprecation.rst
Added TL;DR section and visuals for workflow and best practices. Removed part of "process states" section and incorporated that text directly into the workflow visual.
> Updates to OEP-21

- oeps/oep-templates/adr-based-template.rst
- oeps/oep-templates/external-link-template.rst
- oeps/oep-templates/pep-based-template.rst
None of the templates had Provisional as one of the status choices.  Now they do.
> chore: add Provisional as a status choice to the templates

- oeps/oep-0005/decisions/0001-location-of-decentralized-docs.rst
- oeps/oep-0005/decisions/0002-why-decentralized-devstack.rst
- oeps/oep-0005/decisions/0005-centralized-devstack.rst
We are reversing the previous decisions around decentralized devstack.
This is the ADR to record this new decision.
> doc: Add decision for centralized devstack.

- oeps/oep-0037-bp-test-data.rst
- oeps/oep-0037/decisions/0001-yaml-centralization.rst
- oeps/oep-0037/decisions/0002-remote-dev-data-generation.rst
- oeps/oep-0037/decisions/0003-data-creation-functions.rst
These are some of the decisions made during/after poc of OEP-37: https://openedx.atlassian.net/wiki/spaces/AC/pages/2513076453/OEP-37+Test+Data+implementation
> docs: documenting new decisions

- oeps/oep-0017-bp-feature-toggles.rst
Fixes minor formatting issue in the changelog of
OEP-17.
> docs: fix formatting issue

- oeps/oep-0032-arch-unique-identifier-for-users.rst
Fixes a bad link to another OEP.
> docs: fix bad link

- oeps/oep-0037-bp-test-data.rst
- oeps/oep-0037/decisions/0004-defer-remote-dev-data-generation.rst
See `oep-37/decisions/0004-...` for more details.
> doc: Mark OEP-37 as deferred.

- LICENSE
All public github repositories should have a license. This adds the appropriate license for this repository.
> docs: adding License

- Makefile
- requirements/base.txt
- requirements/common_constraints.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/pip_tools.txt
This will fix the bullets in the OEPs on readthedocs (CENG-124).
> build: add common_constraint.txt

- oeps/oep-0019-bp-developer-documentation.rst
Make the decisions being made by this OEP clear and easy to find at the
top of the document.
> docs: Update oep-19 intro and decisions for clarity.

- oeps/oep-0042-bp-authentication.rst
Adds a link to an exisiting document on oAuth2 and Mobile.
> docs: add oauth2 and mobile link

- oeps/best-practices/oep-0051-bp-conventional-commits.rst
Future amenders of this document should understand what tooling is in
place.
> docs(oep-51): add a Tooling section describing our current tooling

- oeps/processes/oep-0021-proc-deprecation.rst
Add a note to clarify that we really want you to use the templates, but what keyword to use in case you don't wanna.
> OEP-22 Add Clarifying Note

- oeps/processes/oep-0001.rst
> OEP-1 Add tl;dr section to OEP-1

- oeps/processes/oep-0010-proc-openedx-releases.rst
- oeps/processes/oep-0021-proc-deprecation.rst
- oeps/processes/oep-0025-proc-incremental-improvements.rst
- oeps/processes/oep-0054-core-contributors.rst
Resolves openedx/tcril-engineering#133
> docs: Add links to PR discussion for process OEP changelogs

- oeps/architectural-decisions/oep-0041-arch-async-server-event-messaging.rst
Enhance "Architectural Goals" section and minor edits.
Note: This is being pulled from https://github.com/openedx/open-edx-proposals/pull/233 so that it can land faster.
> [OEP-41 - Update] docs: enhance architectural goals section

- oeps/architectural-decisions/oep-0052-arch-event-bus-architecture.rst
This PR opens review on an existing OEP PR: https://github.com/openedx/open-edx-proposals/pull/324
> squash! add arbiter and put under review

- oeps/best-practices/oep-0019-bp-developer-documentation.rst
This is where I expected to find an ADR template, and there wasn’t one.
Now I’ve added one! This template is copied from a suggestion by Ben
Holt, with my addition of an "Options Considered" section.
> docs: Add ADR template to oep-0019

- oeps/processes/oep-0021-proc-deprecation.rst
Add some notes and a link to highlight the 
usefulness of monitoring for the OEP-21 DEPR
process.
> docs: update OEP-21 on DEPR with monitoring link

- oeps/architectural-decisions/oep-0050-hooks-extension-framework.rst
This PR adds the latest documentation to the OEP-50.
> docs: update OEP-50 so reflects latest documentation

- oeps/processes/oep-0055/decisions/0001-use-backstage-to-support-maintainers.rst
From https://github.com/openedx/edx-rest-api-client/pull/231#issuecomment-1242311625 .
> docs: clarify some of the example catalog-info.yaml entries

- oeps/processes/oep-0055/decisions/0001-use-backstage-to-support-maintainers.rst
closes: https://github.com/openedx/tcril-engineering/issues/464
> docs: Update the help text on the owner attribute.

- oeps/architectural-decisions/oep-0026-arch-realtime-events.rst
As this is provisional I am becoming the aribiter to own getting this moved forward to be accepted or abandoned.
> fix: replacing departed arbiter

- oeps/index.rst
> fix(refactor): pr #385 removed sidebar categories

- oeps/processes/oep-0001.rst
Oops... see #387 for discussion.
> fix: Add changelog description for #387.

- oeps/processes/oep-0060-proc-sec-group.rst
Add information how the SWG handles:
- Security scoring
- Vulnerabilities for operators
- Follow up on remediation & on-call transition
- Disagreements on severity classification (and associated SLA)
- Temporary private forks
- Confidentiality
- Disclosure timeline
- Annual security survey
> docs: add cvss info and suggest further procedural details

- catalog-info.yaml
I tried my best to follow [OEP-55](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055/decisions/0001-use-backstage-to-support-maintainers.html). @feanil could you take a look?
> Add Backstage info file

- oeps/architectural-decisions/oep-0014-proc-archive-repos.rst
- oeps/architectural-decisions/oep-0026-arch-realtime-events.rst
- oeps/architectural-decisions/oep-0031-arch-i18n.rst
- oeps/architectural-decisions/oep-0058-arch-translations-management.rst
- oeps/archived/oep-0034-bp-lint-amnesty.rst
- oeps/best-practices/oep-0037-bp-test-data.rst
- oeps/conf.py
- oeps/processes/oep-0001.rst
- oeps/processes/oep-0021-proc-deprecation.rst
- oeps/processes/oep-0054-core-contributors.rst
- oeps/processes/oep-0055-proc-project-maintainers.rst
- oeps/processes/oep-0055/decisions/0001-use-backstage-to-support-maintainers.rst
- oeps/processes/oep-0056-proc-architectural-advisory-process.rst
- oeps/processes/oep-0057-proc-core-product.rst
- oeps/processes/oep-0060-proc-sec-group.rst
Separated out into three commits the sed commands I used. I will squash prior to merging.
> Relpace tCRIL References with Axim references

- oeps/best-practices/oep-0017-bp-feature-toggles.rst
It just update refrence to a  wiki url.
> docs: update url refrence

- oeps/best-practices/oep-0011-bp-FED-technology.rst
> docs: deprecate enzyme

- oeps/architectural-decisions/oep-0003-arch-async-tasks.rst
- oeps/architectural-decisions/oep-0006-arch-context-xblock-fields.rst
- oeps/architectural-decisions/oep-0026-arch-realtime-events.rst
- oeps/architectural-decisions/oep-0026/caliper-realtime-events.rst
- oeps/architectural-decisions/oep-0031-arch-i18n.rst
- oeps/architectural-decisions/oep-0032-arch-unique-identifier-for-users.rst
- oeps/architectural-decisions/oep-0041-arch-async-server-event-messaging.rst
- oeps/architectural-decisions/oep-0045/decisions/0001-tutor-as-replacement-for-edx-configuration.rst
- oeps/architectural-decisions/oep-0045/decisions/0002-helm-for-multi-instance-k8s.rst
- oeps/archived/oep-0005/decisions/0004-data-dump.rst
- oeps/archived/oep-0005/decisions/0005-centralized-devstack.rst
- oeps/archived/oep-0011-bp-FED-technology.rst
- oeps/best-practices/oep-0017-bp-feature-toggles.rst
- oeps/best-practices/oep-0022-bp-django-caches.rst
- oeps/best-practices/oep-0037-bp-test-data.rst
- oeps/best-practices/oep-0037/decisions/0001-yaml-centralization.rst
- oeps/best-practices/oep-0037/decisions/0003-data-creation-functions.rst
- oeps/best-practices/oep-0066-bp-authorization.rst
- oeps/best-practices/oep-0066/Open_edX_Auth_Overview_Table.rst
- oeps/best-practices/oep-0066/Open_edX_Authorization_Explicit_Roles_Table.rst
- oeps/best-practices/oep-0067-bp-tools-and-technology.rst
- oeps/best-practices/oep-0067/decisions/frontend/0001-react.rst
- oeps/best-practices/oep-0067/decisions/frontend/0004-js-ecma.rst
- oeps/processes/oep-0001.rst
- oeps/processes/oep-0054-core-contributors.rst
- oeps/processes/oep-0055-proc-project-maintainers.rst
- oeps/processes/oep-0055/decisions/0002-maintainership-transfer-process.rst
- oeps/processes/oep-0055/decisions/0003-readme-specification.rst
- oeps/processes/oep-0056-proc-architectural-advisory-process.rst
- oeps/processes/oep-0060-proc-sec-group.rst
I was reading one of the OPEs and noticed some typos, so here we are :)
> chore: fixed typos

- oeps/processes/oep-0055/decisions/0003-readme-specification.rst
This follows some discussion in the cookiecutters repo: https://github.com/openedx/edx-cookiecutters/pull/405
> docs: Tweak suggested heading a bit

- oeps/architectural-decisions/oep-0045-arch-ops-and-config.rst
- oeps/architectural-decisions/oep-0045/decisions/0001-tutor-as-replacement-for-edx-configuration.rst
- oeps/architectural-decisions/oep-0045/decisions/0002-helm-for-multi-instance-k8s.rst
this PR marks officially what has been accepted by the community for quite some time already.
- tutor is the official installation mechanism
- the openedx-k8s-harmony project was launched and its under maintenance by members of the large-instances-wg
> chore: marking as accepted oep 45 and its consequences

- oeps/architectural-decisions/oep-0032-arch-unique-identifier-for-users.rst
> docs: Put OEP-32 in Needs Revision status

- .github/workflows/ci.yml
Addresses https://github.com/openedx/open-edx-proposals/issues/623
> build: Use ubuntu-latest for CI

- oeps/architectural-decisions/oep-0050-hooks-extension-framework.rst
- oeps/conf.py
Fixes https://github.com/openedx/open-edx-proposals/issues/653
> fix: reference new hooks documentation location instead

- oeps/architectural-decisions/oep-0003-arch-async-tasks.rst
> Mark OEP-3 as Accepted (Addresses #669)

- oeps/best-practices/oep-0067-bp-tools-and-technology.rst
Addresses #480
Build link: https://docsopenedxorg--675.org.readthedocs.build/projects/openedx-proposals/en/675/best-practices/oep-0067-bp-tools-and-technology.html
> docs: Update OEP-67 - use CSS variables, DEPR tech radar

- oeps/archived/oep-0023-style-customization.rst
Ref https://github.com/openedx/edx-documentation/issues/2339
> docs: Update links to installing and configuring guide

- oeps/architectural-decisions/oep-0015-arch-course-wide-js.rst
Resolves #671
Ref: https://github.com/openedx/edx-platform/pull/28411 added docs for this feature.
> docs: Mark OEP-15 as Accepted; add Change History
